
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `table_kpi_marketing` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model table_kpi_marketing
 * 
 */
export type table_kpi_marketingModel = runtime.Types.Result.DefaultSelection<Prisma.$table_kpi_marketingPayload>

export type AggregateTable_kpi_marketing = {
  _count: Table_kpi_marketingCountAggregateOutputType | null
  _avg: Table_kpi_marketingAvgAggregateOutputType | null
  _sum: Table_kpi_marketingSumAggregateOutputType | null
  _min: Table_kpi_marketingMinAggregateOutputType | null
  _max: Table_kpi_marketingMaxAggregateOutputType | null
}

export type Table_kpi_marketingAvgAggregateOutputType = {
  id: number | null
}

export type Table_kpi_marketingSumAggregateOutputType = {
  id: number | null
}

export type Table_kpi_marketingMinAggregateOutputType = {
  id: number | null
  tasklist: string | null
  kpi: string | null
  karyawan: string | null
  deadline: Date | null
  aktual: Date | null
}

export type Table_kpi_marketingMaxAggregateOutputType = {
  id: number | null
  tasklist: string | null
  kpi: string | null
  karyawan: string | null
  deadline: Date | null
  aktual: Date | null
}

export type Table_kpi_marketingCountAggregateOutputType = {
  id: number
  tasklist: number
  kpi: number
  karyawan: number
  deadline: number
  aktual: number
  _all: number
}


export type Table_kpi_marketingAvgAggregateInputType = {
  id?: true
}

export type Table_kpi_marketingSumAggregateInputType = {
  id?: true
}

export type Table_kpi_marketingMinAggregateInputType = {
  id?: true
  tasklist?: true
  kpi?: true
  karyawan?: true
  deadline?: true
  aktual?: true
}

export type Table_kpi_marketingMaxAggregateInputType = {
  id?: true
  tasklist?: true
  kpi?: true
  karyawan?: true
  deadline?: true
  aktual?: true
}

export type Table_kpi_marketingCountAggregateInputType = {
  id?: true
  tasklist?: true
  kpi?: true
  karyawan?: true
  deadline?: true
  aktual?: true
  _all?: true
}

export type Table_kpi_marketingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which table_kpi_marketing to aggregate.
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of table_kpi_marketings to fetch.
   */
  orderBy?: Prisma.table_kpi_marketingOrderByWithRelationInput | Prisma.table_kpi_marketingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.table_kpi_marketingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` table_kpi_marketings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` table_kpi_marketings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned table_kpi_marketings
  **/
  _count?: true | Table_kpi_marketingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Table_kpi_marketingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Table_kpi_marketingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Table_kpi_marketingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Table_kpi_marketingMaxAggregateInputType
}

export type GetTable_kpi_marketingAggregateType<T extends Table_kpi_marketingAggregateArgs> = {
      [P in keyof T & keyof AggregateTable_kpi_marketing]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTable_kpi_marketing[P]>
    : Prisma.GetScalarType<T[P], AggregateTable_kpi_marketing[P]>
}




export type table_kpi_marketingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.table_kpi_marketingWhereInput
  orderBy?: Prisma.table_kpi_marketingOrderByWithAggregationInput | Prisma.table_kpi_marketingOrderByWithAggregationInput[]
  by: Prisma.Table_kpi_marketingScalarFieldEnum[] | Prisma.Table_kpi_marketingScalarFieldEnum
  having?: Prisma.table_kpi_marketingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Table_kpi_marketingCountAggregateInputType | true
  _avg?: Table_kpi_marketingAvgAggregateInputType
  _sum?: Table_kpi_marketingSumAggregateInputType
  _min?: Table_kpi_marketingMinAggregateInputType
  _max?: Table_kpi_marketingMaxAggregateInputType
}

export type Table_kpi_marketingGroupByOutputType = {
  id: number
  tasklist: string
  kpi: string
  karyawan: string
  deadline: Date
  aktual: Date
  _count: Table_kpi_marketingCountAggregateOutputType | null
  _avg: Table_kpi_marketingAvgAggregateOutputType | null
  _sum: Table_kpi_marketingSumAggregateOutputType | null
  _min: Table_kpi_marketingMinAggregateOutputType | null
  _max: Table_kpi_marketingMaxAggregateOutputType | null
}

export type GetTable_kpi_marketingGroupByPayload<T extends table_kpi_marketingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Table_kpi_marketingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Table_kpi_marketingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Table_kpi_marketingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Table_kpi_marketingGroupByOutputType[P]>
      }
    >
  >



export type table_kpi_marketingWhereInput = {
  AND?: Prisma.table_kpi_marketingWhereInput | Prisma.table_kpi_marketingWhereInput[]
  OR?: Prisma.table_kpi_marketingWhereInput[]
  NOT?: Prisma.table_kpi_marketingWhereInput | Prisma.table_kpi_marketingWhereInput[]
  id?: Prisma.IntFilter<"table_kpi_marketing"> | number
  tasklist?: Prisma.StringFilter<"table_kpi_marketing"> | string
  kpi?: Prisma.StringFilter<"table_kpi_marketing"> | string
  karyawan?: Prisma.StringFilter<"table_kpi_marketing"> | string
  deadline?: Prisma.DateTimeFilter<"table_kpi_marketing"> | Date | string
  aktual?: Prisma.DateTimeFilter<"table_kpi_marketing"> | Date | string
}

export type table_kpi_marketingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tasklist?: Prisma.SortOrder
  kpi?: Prisma.SortOrder
  karyawan?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  aktual?: Prisma.SortOrder
}

export type table_kpi_marketingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.table_kpi_marketingWhereInput | Prisma.table_kpi_marketingWhereInput[]
  OR?: Prisma.table_kpi_marketingWhereInput[]
  NOT?: Prisma.table_kpi_marketingWhereInput | Prisma.table_kpi_marketingWhereInput[]
  tasklist?: Prisma.StringFilter<"table_kpi_marketing"> | string
  kpi?: Prisma.StringFilter<"table_kpi_marketing"> | string
  karyawan?: Prisma.StringFilter<"table_kpi_marketing"> | string
  deadline?: Prisma.DateTimeFilter<"table_kpi_marketing"> | Date | string
  aktual?: Prisma.DateTimeFilter<"table_kpi_marketing"> | Date | string
}, "id">

export type table_kpi_marketingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tasklist?: Prisma.SortOrder
  kpi?: Prisma.SortOrder
  karyawan?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  aktual?: Prisma.SortOrder
  _count?: Prisma.table_kpi_marketingCountOrderByAggregateInput
  _avg?: Prisma.table_kpi_marketingAvgOrderByAggregateInput
  _max?: Prisma.table_kpi_marketingMaxOrderByAggregateInput
  _min?: Prisma.table_kpi_marketingMinOrderByAggregateInput
  _sum?: Prisma.table_kpi_marketingSumOrderByAggregateInput
}

export type table_kpi_marketingScalarWhereWithAggregatesInput = {
  AND?: Prisma.table_kpi_marketingScalarWhereWithAggregatesInput | Prisma.table_kpi_marketingScalarWhereWithAggregatesInput[]
  OR?: Prisma.table_kpi_marketingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.table_kpi_marketingScalarWhereWithAggregatesInput | Prisma.table_kpi_marketingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"table_kpi_marketing"> | number
  tasklist?: Prisma.StringWithAggregatesFilter<"table_kpi_marketing"> | string
  kpi?: Prisma.StringWithAggregatesFilter<"table_kpi_marketing"> | string
  karyawan?: Prisma.StringWithAggregatesFilter<"table_kpi_marketing"> | string
  deadline?: Prisma.DateTimeWithAggregatesFilter<"table_kpi_marketing"> | Date | string
  aktual?: Prisma.DateTimeWithAggregatesFilter<"table_kpi_marketing"> | Date | string
}

export type table_kpi_marketingCreateInput = {
  tasklist: string
  kpi: string
  karyawan: string
  deadline: Date | string
  aktual: Date | string
}

export type table_kpi_marketingUncheckedCreateInput = {
  id?: number
  tasklist: string
  kpi: string
  karyawan: string
  deadline: Date | string
  aktual: Date | string
}

export type table_kpi_marketingUpdateInput = {
  tasklist?: Prisma.StringFieldUpdateOperationsInput | string
  kpi?: Prisma.StringFieldUpdateOperationsInput | string
  karyawan?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aktual?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type table_kpi_marketingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tasklist?: Prisma.StringFieldUpdateOperationsInput | string
  kpi?: Prisma.StringFieldUpdateOperationsInput | string
  karyawan?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aktual?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type table_kpi_marketingCreateManyInput = {
  id?: number
  tasklist: string
  kpi: string
  karyawan: string
  deadline: Date | string
  aktual: Date | string
}

export type table_kpi_marketingUpdateManyMutationInput = {
  tasklist?: Prisma.StringFieldUpdateOperationsInput | string
  kpi?: Prisma.StringFieldUpdateOperationsInput | string
  karyawan?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aktual?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type table_kpi_marketingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tasklist?: Prisma.StringFieldUpdateOperationsInput | string
  kpi?: Prisma.StringFieldUpdateOperationsInput | string
  karyawan?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  aktual?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type table_kpi_marketingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tasklist?: Prisma.SortOrder
  kpi?: Prisma.SortOrder
  karyawan?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  aktual?: Prisma.SortOrder
}

export type table_kpi_marketingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type table_kpi_marketingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tasklist?: Prisma.SortOrder
  kpi?: Prisma.SortOrder
  karyawan?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  aktual?: Prisma.SortOrder
}

export type table_kpi_marketingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tasklist?: Prisma.SortOrder
  kpi?: Prisma.SortOrder
  karyawan?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  aktual?: Prisma.SortOrder
}

export type table_kpi_marketingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type table_kpi_marketingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tasklist?: boolean
  kpi?: boolean
  karyawan?: boolean
  deadline?: boolean
  aktual?: boolean
}, ExtArgs["result"]["table_kpi_marketing"]>

export type table_kpi_marketingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tasklist?: boolean
  kpi?: boolean
  karyawan?: boolean
  deadline?: boolean
  aktual?: boolean
}, ExtArgs["result"]["table_kpi_marketing"]>

export type table_kpi_marketingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tasklist?: boolean
  kpi?: boolean
  karyawan?: boolean
  deadline?: boolean
  aktual?: boolean
}, ExtArgs["result"]["table_kpi_marketing"]>

export type table_kpi_marketingSelectScalar = {
  id?: boolean
  tasklist?: boolean
  kpi?: boolean
  karyawan?: boolean
  deadline?: boolean
  aktual?: boolean
}

export type table_kpi_marketingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tasklist" | "kpi" | "karyawan" | "deadline" | "aktual", ExtArgs["result"]["table_kpi_marketing"]>

export type $table_kpi_marketingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "table_kpi_marketing"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tasklist: string
    kpi: string
    karyawan: string
    deadline: Date
    aktual: Date
  }, ExtArgs["result"]["table_kpi_marketing"]>
  composites: {}
}

export type table_kpi_marketingGetPayload<S extends boolean | null | undefined | table_kpi_marketingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload, S>

export type table_kpi_marketingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<table_kpi_marketingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Table_kpi_marketingCountAggregateInputType | true
  }

export interface table_kpi_marketingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['table_kpi_marketing'], meta: { name: 'table_kpi_marketing' } }
  /**
   * Find zero or one Table_kpi_marketing that matches the filter.
   * @param {table_kpi_marketingFindUniqueArgs} args - Arguments to find a Table_kpi_marketing
   * @example
   * // Get one Table_kpi_marketing
   * const table_kpi_marketing = await prisma.table_kpi_marketing.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends table_kpi_marketingFindUniqueArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Table_kpi_marketing that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {table_kpi_marketingFindUniqueOrThrowArgs} args - Arguments to find a Table_kpi_marketing
   * @example
   * // Get one Table_kpi_marketing
   * const table_kpi_marketing = await prisma.table_kpi_marketing.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends table_kpi_marketingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Table_kpi_marketing that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {table_kpi_marketingFindFirstArgs} args - Arguments to find a Table_kpi_marketing
   * @example
   * // Get one Table_kpi_marketing
   * const table_kpi_marketing = await prisma.table_kpi_marketing.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends table_kpi_marketingFindFirstArgs>(args?: Prisma.SelectSubset<T, table_kpi_marketingFindFirstArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Table_kpi_marketing that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {table_kpi_marketingFindFirstOrThrowArgs} args - Arguments to find a Table_kpi_marketing
   * @example
   * // Get one Table_kpi_marketing
   * const table_kpi_marketing = await prisma.table_kpi_marketing.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends table_kpi_marketingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, table_kpi_marketingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Table_kpi_marketings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {table_kpi_marketingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Table_kpi_marketings
   * const table_kpi_marketings = await prisma.table_kpi_marketing.findMany()
   * 
   * // Get first 10 Table_kpi_marketings
   * const table_kpi_marketings = await prisma.table_kpi_marketing.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const table_kpi_marketingWithIdOnly = await prisma.table_kpi_marketing.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends table_kpi_marketingFindManyArgs>(args?: Prisma.SelectSubset<T, table_kpi_marketingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Table_kpi_marketing.
   * @param {table_kpi_marketingCreateArgs} args - Arguments to create a Table_kpi_marketing.
   * @example
   * // Create one Table_kpi_marketing
   * const Table_kpi_marketing = await prisma.table_kpi_marketing.create({
   *   data: {
   *     // ... data to create a Table_kpi_marketing
   *   }
   * })
   * 
   */
  create<T extends table_kpi_marketingCreateArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingCreateArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Table_kpi_marketings.
   * @param {table_kpi_marketingCreateManyArgs} args - Arguments to create many Table_kpi_marketings.
   * @example
   * // Create many Table_kpi_marketings
   * const table_kpi_marketing = await prisma.table_kpi_marketing.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends table_kpi_marketingCreateManyArgs>(args?: Prisma.SelectSubset<T, table_kpi_marketingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Table_kpi_marketings and returns the data saved in the database.
   * @param {table_kpi_marketingCreateManyAndReturnArgs} args - Arguments to create many Table_kpi_marketings.
   * @example
   * // Create many Table_kpi_marketings
   * const table_kpi_marketing = await prisma.table_kpi_marketing.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Table_kpi_marketings and only return the `id`
   * const table_kpi_marketingWithIdOnly = await prisma.table_kpi_marketing.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends table_kpi_marketingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, table_kpi_marketingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Table_kpi_marketing.
   * @param {table_kpi_marketingDeleteArgs} args - Arguments to delete one Table_kpi_marketing.
   * @example
   * // Delete one Table_kpi_marketing
   * const Table_kpi_marketing = await prisma.table_kpi_marketing.delete({
   *   where: {
   *     // ... filter to delete one Table_kpi_marketing
   *   }
   * })
   * 
   */
  delete<T extends table_kpi_marketingDeleteArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingDeleteArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Table_kpi_marketing.
   * @param {table_kpi_marketingUpdateArgs} args - Arguments to update one Table_kpi_marketing.
   * @example
   * // Update one Table_kpi_marketing
   * const table_kpi_marketing = await prisma.table_kpi_marketing.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends table_kpi_marketingUpdateArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingUpdateArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Table_kpi_marketings.
   * @param {table_kpi_marketingDeleteManyArgs} args - Arguments to filter Table_kpi_marketings to delete.
   * @example
   * // Delete a few Table_kpi_marketings
   * const { count } = await prisma.table_kpi_marketing.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends table_kpi_marketingDeleteManyArgs>(args?: Prisma.SelectSubset<T, table_kpi_marketingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Table_kpi_marketings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {table_kpi_marketingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Table_kpi_marketings
   * const table_kpi_marketing = await prisma.table_kpi_marketing.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends table_kpi_marketingUpdateManyArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Table_kpi_marketings and returns the data updated in the database.
   * @param {table_kpi_marketingUpdateManyAndReturnArgs} args - Arguments to update many Table_kpi_marketings.
   * @example
   * // Update many Table_kpi_marketings
   * const table_kpi_marketing = await prisma.table_kpi_marketing.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Table_kpi_marketings and only return the `id`
   * const table_kpi_marketingWithIdOnly = await prisma.table_kpi_marketing.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends table_kpi_marketingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Table_kpi_marketing.
   * @param {table_kpi_marketingUpsertArgs} args - Arguments to update or create a Table_kpi_marketing.
   * @example
   * // Update or create a Table_kpi_marketing
   * const table_kpi_marketing = await prisma.table_kpi_marketing.upsert({
   *   create: {
   *     // ... data to create a Table_kpi_marketing
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Table_kpi_marketing we want to update
   *   }
   * })
   */
  upsert<T extends table_kpi_marketingUpsertArgs>(args: Prisma.SelectSubset<T, table_kpi_marketingUpsertArgs<ExtArgs>>): Prisma.Prisma__table_kpi_marketingClient<runtime.Types.Result.GetResult<Prisma.$table_kpi_marketingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Table_kpi_marketings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {table_kpi_marketingCountArgs} args - Arguments to filter Table_kpi_marketings to count.
   * @example
   * // Count the number of Table_kpi_marketings
   * const count = await prisma.table_kpi_marketing.count({
   *   where: {
   *     // ... the filter for the Table_kpi_marketings we want to count
   *   }
   * })
  **/
  count<T extends table_kpi_marketingCountArgs>(
    args?: Prisma.Subset<T, table_kpi_marketingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Table_kpi_marketingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Table_kpi_marketing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Table_kpi_marketingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Table_kpi_marketingAggregateArgs>(args: Prisma.Subset<T, Table_kpi_marketingAggregateArgs>): Prisma.PrismaPromise<GetTable_kpi_marketingAggregateType<T>>

  /**
   * Group by Table_kpi_marketing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {table_kpi_marketingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends table_kpi_marketingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: table_kpi_marketingGroupByArgs['orderBy'] }
      : { orderBy?: table_kpi_marketingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, table_kpi_marketingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTable_kpi_marketingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the table_kpi_marketing model
 */
readonly fields: table_kpi_marketingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for table_kpi_marketing.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__table_kpi_marketingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the table_kpi_marketing model
 */
export interface table_kpi_marketingFieldRefs {
  readonly id: Prisma.FieldRef<"table_kpi_marketing", 'Int'>
  readonly tasklist: Prisma.FieldRef<"table_kpi_marketing", 'String'>
  readonly kpi: Prisma.FieldRef<"table_kpi_marketing", 'String'>
  readonly karyawan: Prisma.FieldRef<"table_kpi_marketing", 'String'>
  readonly deadline: Prisma.FieldRef<"table_kpi_marketing", 'DateTime'>
  readonly aktual: Prisma.FieldRef<"table_kpi_marketing", 'DateTime'>
}
    

// Custom InputTypes
/**
 * table_kpi_marketing findUnique
 */
export type table_kpi_marketingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * Filter, which table_kpi_marketing to fetch.
   */
  where: Prisma.table_kpi_marketingWhereUniqueInput
}

/**
 * table_kpi_marketing findUniqueOrThrow
 */
export type table_kpi_marketingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * Filter, which table_kpi_marketing to fetch.
   */
  where: Prisma.table_kpi_marketingWhereUniqueInput
}

/**
 * table_kpi_marketing findFirst
 */
export type table_kpi_marketingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * Filter, which table_kpi_marketing to fetch.
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of table_kpi_marketings to fetch.
   */
  orderBy?: Prisma.table_kpi_marketingOrderByWithRelationInput | Prisma.table_kpi_marketingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for table_kpi_marketings.
   */
  cursor?: Prisma.table_kpi_marketingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` table_kpi_marketings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` table_kpi_marketings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of table_kpi_marketings.
   */
  distinct?: Prisma.Table_kpi_marketingScalarFieldEnum | Prisma.Table_kpi_marketingScalarFieldEnum[]
}

/**
 * table_kpi_marketing findFirstOrThrow
 */
export type table_kpi_marketingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * Filter, which table_kpi_marketing to fetch.
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of table_kpi_marketings to fetch.
   */
  orderBy?: Prisma.table_kpi_marketingOrderByWithRelationInput | Prisma.table_kpi_marketingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for table_kpi_marketings.
   */
  cursor?: Prisma.table_kpi_marketingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` table_kpi_marketings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` table_kpi_marketings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of table_kpi_marketings.
   */
  distinct?: Prisma.Table_kpi_marketingScalarFieldEnum | Prisma.Table_kpi_marketingScalarFieldEnum[]
}

/**
 * table_kpi_marketing findMany
 */
export type table_kpi_marketingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * Filter, which table_kpi_marketings to fetch.
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of table_kpi_marketings to fetch.
   */
  orderBy?: Prisma.table_kpi_marketingOrderByWithRelationInput | Prisma.table_kpi_marketingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing table_kpi_marketings.
   */
  cursor?: Prisma.table_kpi_marketingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` table_kpi_marketings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` table_kpi_marketings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of table_kpi_marketings.
   */
  distinct?: Prisma.Table_kpi_marketingScalarFieldEnum | Prisma.Table_kpi_marketingScalarFieldEnum[]
}

/**
 * table_kpi_marketing create
 */
export type table_kpi_marketingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * The data needed to create a table_kpi_marketing.
   */
  data: Prisma.XOR<Prisma.table_kpi_marketingCreateInput, Prisma.table_kpi_marketingUncheckedCreateInput>
}

/**
 * table_kpi_marketing createMany
 */
export type table_kpi_marketingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many table_kpi_marketings.
   */
  data: Prisma.table_kpi_marketingCreateManyInput | Prisma.table_kpi_marketingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * table_kpi_marketing createManyAndReturn
 */
export type table_kpi_marketingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * The data used to create many table_kpi_marketings.
   */
  data: Prisma.table_kpi_marketingCreateManyInput | Prisma.table_kpi_marketingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * table_kpi_marketing update
 */
export type table_kpi_marketingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * The data needed to update a table_kpi_marketing.
   */
  data: Prisma.XOR<Prisma.table_kpi_marketingUpdateInput, Prisma.table_kpi_marketingUncheckedUpdateInput>
  /**
   * Choose, which table_kpi_marketing to update.
   */
  where: Prisma.table_kpi_marketingWhereUniqueInput
}

/**
 * table_kpi_marketing updateMany
 */
export type table_kpi_marketingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update table_kpi_marketings.
   */
  data: Prisma.XOR<Prisma.table_kpi_marketingUpdateManyMutationInput, Prisma.table_kpi_marketingUncheckedUpdateManyInput>
  /**
   * Filter which table_kpi_marketings to update
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * Limit how many table_kpi_marketings to update.
   */
  limit?: number
}

/**
 * table_kpi_marketing updateManyAndReturn
 */
export type table_kpi_marketingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * The data used to update table_kpi_marketings.
   */
  data: Prisma.XOR<Prisma.table_kpi_marketingUpdateManyMutationInput, Prisma.table_kpi_marketingUncheckedUpdateManyInput>
  /**
   * Filter which table_kpi_marketings to update
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * Limit how many table_kpi_marketings to update.
   */
  limit?: number
}

/**
 * table_kpi_marketing upsert
 */
export type table_kpi_marketingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * The filter to search for the table_kpi_marketing to update in case it exists.
   */
  where: Prisma.table_kpi_marketingWhereUniqueInput
  /**
   * In case the table_kpi_marketing found by the `where` argument doesn't exist, create a new table_kpi_marketing with this data.
   */
  create: Prisma.XOR<Prisma.table_kpi_marketingCreateInput, Prisma.table_kpi_marketingUncheckedCreateInput>
  /**
   * In case the table_kpi_marketing was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.table_kpi_marketingUpdateInput, Prisma.table_kpi_marketingUncheckedUpdateInput>
}

/**
 * table_kpi_marketing delete
 */
export type table_kpi_marketingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
  /**
   * Filter which table_kpi_marketing to delete.
   */
  where: Prisma.table_kpi_marketingWhereUniqueInput
}

/**
 * table_kpi_marketing deleteMany
 */
export type table_kpi_marketingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which table_kpi_marketings to delete
   */
  where?: Prisma.table_kpi_marketingWhereInput
  /**
   * Limit how many table_kpi_marketings to delete.
   */
  limit?: number
}

/**
 * table_kpi_marketing without action
 */
export type table_kpi_marketingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the table_kpi_marketing
   */
  select?: Prisma.table_kpi_marketingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the table_kpi_marketing
   */
  omit?: Prisma.table_kpi_marketingOmit<ExtArgs> | null
}
